### ISSUE TITLE
Improve structure visibility of documentation

### ISSUE THREAD

**Issue by DaniRey** [unic/ScalaWebTest#18]
The documentation is reasonably structured, unfortunately this structure is barely visible for the reader. Ammonite and Thymleaf are good examples.

- Ammonite has an excellent navigation http://www.lihaoyi.com/Ammonite/
- Thymleaf clearly shows the structure http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html

**Comment by olimination** [comment]
Other solution proposals (fyi @FabianMum):
- Using http://scrollmagic.io and a left navigation tree
- Or completely switch to what "Ammonite" is using "Scalatex" http://www.lihaoyi.com/Scalatex/ (but is not really integrated with Github Pages

**Comment by DaniRey** [comment]
Scalatex is a server side solution. The navigation behavior has to be implemented on client side anyway. Therefore Scalatex doesn't solve our problem. Also Github Pages is a must.

I'm open to use scrollmagic.io, although I doubt it is really needed in our case.

**Comment by DaniRey** [comment]
Scalatex is a server side solution. The navigation behavior has to be implemented on client side anyway. Therefore Scalatex doesn't solve our problem. Also Github Pages is a must.

I'm open to use scrollmagic.io, although I doubt it is really needed in our case.

**Comment by DaniRey** [comment]
Thanks @FabianMum for the huge improvements you provided to the visibility of the documentation structure.
