### ISSUE TITLE
Add support for checking http codes

### ISSUE THREAD

**Issue by olimination** [unic/ScalaWebTest#21]
Adding support for checking http codes.

This is useful if you want to check for example the existence of some resource.

This is also useful to test pure Web APIs with proper REST-oriented http codes.

There is for example a possibility to get it like this:
```scala
webRespone = webDriver.getClient.getCurrentWindow.getEnclosedPage.getWebResponse
webResponse.getStatusCode
```

Maybe this is a starting point.

**Comment by DaniRey** [comment]
Implementation is finished. Documentation has to be enhanced. This has to be done in the feature branch for 3.0.0 (otherwise our website documents 3.0.0 before it is released)

**Comment by DaniRey** [comment]
Documentation is tracked with #79
