### ISSUE TITLE
Misfitting Element Order can be misleading

### ISSUE THREAD

**Issue by DaniRey** [unic/ScalaWebTest#42]
Assume the following HtmlElement
```
<h2 class="title">foo</h2>
<p>text</p>
```
and the following gauge definition
```
element fits(
<h2 class="title">foo</h2>
<p>text</p>
<h2 class="title"></h2>
)
```

This will lead to the following error
```
Misfitting Element Order: Wrong order of elements [<h2 class="title">foo</h2>] was found before [<p>text</p>] but expected the other way round.
```
The last part of the gauge definition `<h2 class="title"></h2>` also matches `<h2 class="title">foo</h2>` but in this case it is at the wrong position and therefore a misfit is reported.

The error message should be improved to point out the fact, that the element is either not found, or only found in the wrong position. We should guide the user, by not only showing the element which was found, but also the gauge definition which led to that element being found.

**Comment by DaniRey** [comment]
Ideas for a good wording are very welcome.

**Comment by jenssuhr** [comment]
What about this:
`Misfitting Element Order: [<h2 class="title">foo</h2>] was found before [<p>text</p>], but [<h2 class="title"></h2>] was expected after [<p>text</p>].`

**Comment by DaniRey** [comment]
@jenssuhr Thanks for the idea. It helped me to come up with the following, what do you think.

Misfitting Element Order: Found `<h2 class="title">foo</h2>` when looking for an element matching `<h2 class="title"></h2>`. It didn't fit, because it was found before `<p>text</p>`, but  was expected after it.
