### ISSUE TITLE
Various issues with 2.0.1 : doc , empty jar

### ISSUE THREAD

**Issue by jmvanel** [unic/ScalaWebTest#56]
Doc
- does not mention declaring IntegrationTest config ; see http://www.scala-sbt.org/0.13/docs/Testing.html
-  does not mention `libraryDependencies += "org.scalawebtest" %% "scalawebtest-integration" % "2.0.1" `

The latter jar for scalawebtest-integration 2.0.1 has no .class in it :
 https://search.maven.org/remotecontent?filepath=org/scalawebtest/scalawebtest-integration_2.11/2.0.1/scalawebtest-integration_2.11-2.0.1.jar

**Comment by DaniRey** [comment]
Thank you for that valuable information. I'm currently on holiday and will have a look at this next week.

I hope you are not blocked at the moment. Otherwise I might ping a colleague to resolve this issue.

**Comment by jmvanel** [comment]
Indeed I'm almost blocked at the moment. 
I tried also the Scala 2.12 items , 
but they seem to be even more missing ( just pom present ) : 
https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.scalawebtest%22%20AND%20a%3A%22scalawebtest-bom_2.12%22

So I could generate locally the artifacts from the sources ,
but then I'm not sure that there is not an error here ...

So , if you could ping a colleague to resolve this issue, that would bhe nice !

**Comment by jmvanel** [comment]
So I generated locally the artifacts from the sources ,
`sbt publishLocal` went fine . Seemingly !!!
But it generated also an **empty jar** for the artifact scalawebtest-integration :

```shell
unzip -l /home/jmv/.ivy2/local/org.scalawebtest/scalawebtest-integration_2.12/2.0.2-SNAPSHOT/jars/scalawebtest-integration_2.12.jar 
Archive:  /home/jmv/.ivy2/local/org.scalawebtest/scalawebtest-integration_2.12/2.0.2-SNAPSHOT/jars/scalawebtest-integration_2.12.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
      324  2018-01-24 15:34   META-INF/MANIFEST.MF
---------                     -------
      324                     1 file
```

I don't think I'll have the time to fix this :( .

**Comment by DaniRey** [comment]
Just had a calm moment myself. Did you see the "try it in scastie" links in the documentation? They point to working examples in Scastie, i.e.  https://scastie.scala-lang.org/DaniRey/aOD6RFqwSgynejH7CNl6qQ

Usually your code should depend on the core and not on the integration bundle. The latter contains the integration tests used by scalawebtest, to test itself.

**Comment by jmvanel** [comment]
Refering to the page in doc:
http://www.scalawebtest.org/documentation.html#process 

 The example extends ScalaWebTestBaseSpec, which is really in scalawebtest-integration module : in 
ScalaWebTest/scalawebtest-integration/src/it/scala/org/scalawebtest/integration/ScalaWebTestBaseSpec.scala

So , either the doc is wrong, or your assertion  an hour ago .

**Comment by DaniRey** [comment]
The intent is that one creates a project specific base trait oneself. I use the one from our integration tests as an example. This seems to be misleading and will be changed.

**Comment by DaniRey** [comment]
Here is the part of the documentation, which introduces the idea of a project specific base trait http://www.scalawebtest.org/documentation.html#basetrait
Would you use a  documentation specific base trait introduced in this section, or not use a base trait at all for the rest of the documentation? I guess the latter would be the option. What do you think?

**Comment by jmvanel** [comment]
So, this means that, for "Testing a complete process" , one  extends ScalaWebTestBaseSpec defined above in doc. , and not the class with same name in  scalawebtest-integration module .

And indeed , it works !
MANY thanks !!!

And the doc. was indeed misleading,
since
http://www.scalawebtest.org/documentation.html#usingGauges
includes 

       import org.scalawebtest.integration.ScalaWebTestBaseSpec

which refers to missing and un-needed jar :( .

In http://www.scalawebtest.org/documentation.html#process , it should also remind that the class ScalaWebTestBaseSpec was defined above.
Some people do fly at high altitude in docs :) !

Also , the examples should not be in

    package org.scalawebtest.integration.gauge

which is confusing , but in something like 

    package myTests.scalawebtest

Also , what remains in my original issue is : 

_does not mention declaring IntegrationTest config ; see http://www.scala-sbt.org/0.13/docs/Testing.html_

**Comment by jmvanel** [comment]
Our posts crossed each other !

And yes, the latter would be the option.

**Comment by DaniRey** [comment]
Happy to hear that it works now.

I will try to clarify the documentation once I'm back. I will then ask you for feedback before closing the issue.

**Comment by DaniRey** [comment]
Great, I'll aim for the latter.

**Comment by DaniRey** [comment]
@jmvanel I tried to improve the documentation based on our discussion. Did I address all your concerns? Do you see other parts which are misleading or missing?

**Comment by DaniRey** [comment]
Hi @jmvanel 
I would very much appreciate your feedback to the documentation changes. Was I able to address all your concerns?

**Comment by DaniRey** [comment]
@jmvanel as I didn't hear back, I assume the documentation isn't misleading anymore. Thank you for those valuable questions.
