### ISSUE TITLE
Certificate mismatch on https://scalawebtest.org

### ISSUE THREAD

**Issue by marcel-wiedemeier** [unic/ScalaWebTest#65]
There is a certificate mismatch; seems like no proper certificate has been generated for scalawebtest.org. The issue does not appear on https://www.scalawebtest.org.

See also: https://www.ssllabs.com/ssltest/analyze.html?d=scalawebtest.org&hideResults=on 

This might be related to the domain settings in netlify.

**Comment by DaniRey** [comment]
I switched the primary domain in the netlify configuration to scalawebtest.org and then back to www.scalawebtest.org. This caused netlify to regenerate the SSL certificate. It now contains both domains. 

https://www.ssllabs.com/ssltest/analyze.html?d=scalawebtest.org&hideResults=on now returns an A+ rating 💯
